### ISSUE TITLE
OSX Lock Command?

### ISSUE THREAD

**Issue by mmmerl** [tinytacoteam/zazu-system#7]
Currently zazu-system is using `pmset displaysleepnow` as the OSX Lock command. If the user doesn't have their privacy setting to "Require password immediately after sleep or screen saver changes", this command won't actually password protect their computer (until whatever time/setting they have set).

The `Login Window...` command in the user switcher and Alfred both used this command:
```
/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend
```

Only caveat with this one, is (I'm pretty sure) it will suspend any network activity as well.

Thoughts? Should we use a command that will guarantee a Lock, but suspend network activity?

**Comment by bayleedev** [comment]
I think this is a great solution, I'm pushing a commit now.
