### ISSUE TITLE
Stickies overriding Lock Computer shortcut

### ISSUE THREAD

**Issue by vallamost** [tinytacoteam/zazu-system#8]
Does anyone else have this issue? It seems illogical since 'lock' isn't in any of the words.

https://i.imgur.com/RggcySp.png

OSX El Capitan version 10.11.6

**Comment by bayleedev** [comment]
It looks like "lock" is mixed between two apps. My guess is that you clicked on "stickies" and gave it a higher priority. If you click "lock" a few times it'll appear higher.
